{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "client.serviceAccountName" . }}
  labels:
{{ include "client.labels" . | indent 4 }}
{{- end -}}
